/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#71d7cf",
        "primary": "#b7122a",
        "on-tertiary-fixed": "#00201e",
        "inverse-on-surface": "#f3f0ef",
        "error-container": "#ffdad6",
        "surface-container-high": "#eae7e7",
        "secondary-container": "#fcd400",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00837c",
        "on-background": "#1b1b1b",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "outline": "#8f6f6e",
        "tertiary-fixed": "#8ef4eb",
        "primary-fixed-dim": "#ffb3b1",
        "on-surface": "#1b1b1b",
        "inverse-primary": "#ffb3b1",
        "on-surface-variant": "#5b403f",
        "background": "#fcf9f8",
        "tertiary": "#006762",
        "on-tertiary-fixed-variant": "#00504c",
        "on-secondary-fixed": "#221b00",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-container": "#6e5c00",
        "surface-container-low": "#f6f3f2",
        "on-secondary-fixed-variant": "#544600",
        "secondary": "#705d00",
        "surface-container": "#f0eded",
        "on-primary-fixed": "#410007",
        "on-primary-fixed-variant": "#92001c",
        "secondary-fixed": "#ffe16d",
        "on-tertiary-container": "#f3fffd",
        "surface": "#fcf9f8",
        "surface-dim": "#dcd9d9",
        "on-error": "#ffffff",
        "surface-tint": "#bb162c",
        "surface-bright": "#fcf9f8",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e5e2e1",
        "on-primary-container": "#fffbff",
        "inverse-surface": "#313030",
        "primary-fixed": "#ffdad8",
        "secondary-fixed-dim": "#e9c400",
        "primary-container": "#db313f",
        "error": "#ba1a1a",
        "outline-variant": "#e4bebc",
        "zomato-red": "#E23744"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem"
      },
      spacing: {
        "container-max": "1280px",
        "stack-sm": "8px",
        "stack-lg": "32px",
        "edge-margin": "32px",
        "edge-margin-mobile": "20px",
        "stack-md": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "label-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
